export const StatusResponse = {
  SUCCESS: 1,
  FAIL: 2,
  FOBBIDEN: 3,
  NOTFOUND: 4,
  EXISTS_USERNAME: 5,
  EXISTS_EMAIL: 6,
  NOT_EXISTS_ROLE: 8,
  USERNAME_OR_PASSWORD_IS_NOT_CORRECT: 9,
  PASSWORD_INCORRECT: 10,
  TOKEN_CLOUDFLARE_IS_REQUIRE: 11,
  TOKEN_CLOUDFLARE_NOT_VALID: 12,
};
